# Generated by Django 3.2.8 on 2021-10-31 13:24

from typing import List, Tuple
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='AptoideApp',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=150)),
                ('downloads_number', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'aptoide app',
            },
        ),
    ]
